# Generated by Django 3.2.7 on 2021-09-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Имя учителя')),
            ],
        ),
        migrations.CreateModel(
            name='PairTimetableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название пары')),
                ('type', models.CharField(max_length=500, verbose_name='Тип пары')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('place', models.CharField(max_length=500, verbose_name='Аудитория')),
                ('date', models.DateField(verbose_name='Дата пары')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Направление', to='timetable.directionmodel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Группа', to='timetable.groupmodel')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Институт', to='timetable.institutemodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Учитель', to='timetable.teachermodel')),
            ],
        ),
    ]
